
name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          # Extract version from package.json
          VERSION=$(node -p "require('./package.json').version")

          # Replace version placeholder in README.md with the extracted version
          sed -i "s/\[![Version\]\(.*\)\]/[![Version]($VERSION)]/g" README.md

          # Commit and push changes
          git config --local user.email "samprince.franklink2020@vitstudent.ac.in"
          git config --local user.name "SamPrinceFranklin"
          git commit -am "Update version in README.md"
          git push
